# Local testing with Lambda RIE
FROM paguebem-api-test:local

# Copiar Lambda RIE
COPY --from=public.ecr.aws/lambda/provided:al2 /lambda-entrypoint.sh /
COPY --from=public.ecr.aws/lambda/provided:al2 /usr/local/bin/aws-lambda-rie /usr/local/bin/

RUN chmod +x /lambda-entrypoint.sh /usr/local/bin/aws-lambda-rie

ENTRYPOINT [ "/lambda-entrypoint.sh" ]
CMD [ "lambda_function.lambda_handler" ]
